import { describe, expect, it, vi } from "vitest";
import { createSupportService } from "../src/modules/support/support.service.js";
const member = { id: "user-1", role: "member" };
describe("support service", () => {
  it("scopes a member ticket list to that member", async () => { const repository = { memberByUser: vi.fn().mockResolvedValue({ id: "member-1" }), tickets: vi.fn().mockResolvedValue([]) }; await createSupportService({ repository, auditService: { record: vi.fn() } }).list(member); expect(repository.tickets).toHaveBeenCalledWith({ member_id: "member-1" }); });
  it("does not let a member respond as staff", async () => { const repository = { memberByUser: vi.fn().mockResolvedValue({ id: "member-1" }), ticket: vi.fn().mockResolvedValue({ id: "ticket-1", member_id: "member-1" }) }; await expect(createSupportService({ repository, auditService: { record: vi.fn() } }).respond("ticket-1", { body: "Xin hỗ trợ" }, member)).rejects.toMatchObject({ code: "SUPPORT_RESPONSE_FORBIDDEN" }); });
  it("persists the normal priority accepted by the member form", async () => { const repository = { memberByUser: vi.fn().mockResolvedValue({ id: "member-1" }), create: vi.fn().mockResolvedValue({ id: "ticket-1" }) }; const auditService = { record: vi.fn() }; await createSupportService({ repository, auditService }).create({ subject: "Cần hỗ trợ", body: "Nội dung kiểm thử", priority: "normal" }, member); expect(repository.create).toHaveBeenCalledWith(expect.objectContaining({ member_id: "member-1", priority: "normal" })); });
  it("assigns a ticket owner and moves an open ticket to in progress", async () => { const repository = { ticket: vi.fn().mockResolvedValue({ id: "ticket-1", status: "open" }), update: vi.fn().mockResolvedValue({ id: "ticket-1", assigned_to: "staff-1", status: "in_progress" }) }; const auditService = { record: vi.fn() }; await expect(createSupportService({ repository, auditService }).assignSelf("ticket-1", { id: "staff-1", role: "receptionist" })).resolves.toMatchObject({ assigned_to: "staff-1", status: "in_progress" }); expect(repository.update).toHaveBeenCalledWith("ticket-1", { assigned_to: "staff-1", status: "in_progress" }); });
  it("creates a member notification when staff responds", async () => { const repository = { ticket: vi.fn().mockResolvedValue({ id: "ticket-1", ticket_code: "SUP-01", member_id: "member-1", status: "open", assigned_to: null }), respond: vi.fn().mockResolvedValue({ id: "response-1" }), update: vi.fn(), memberUserId: vi.fn().mockResolvedValue("member-user-1"), notifyUser: vi.fn() }; await createSupportService({ repository, auditService: { record: vi.fn() } }).respond("ticket-1", { body: "Chúng tôi đã tiếp nhận.", status: "in_progress" }, { id: "staff-1", role: "receptionist" }); expect(repository.notifyUser).toHaveBeenCalledWith("member-user-1", expect.objectContaining({ title: "Phản hồi yêu cầu SUP-01" })); });
});
