import { Bell, CalendarDays, ClipboardCheck, CreditCard, Dumbbell, LayoutDashboard, LogOut, Package, ReceiptText, Users, UserRoundCog } from "lucide-react";
import { Button } from "../ui/Button.jsx";
import "./AppShell.css";

const icons = { dashboard: LayoutDashboard, members: Users, registrations: UserRoundCog, packages: Package, classes: CalendarDays, bookings: ReceiptText, attendance: ClipboardCheck, payments: CreditCard, training: Dumbbell, staff: UserRoundCog, reports: LayoutDashboard };

export function AppShell({ children, currentView, navigation, notifications, onLogout, onNavigate, onReadNotification, roleLabel }) {
  return <div className="app-shell"><aside className="app-sidebar"><div className="app-sidebar__brand"><span>SC</span><div><strong>Sports Center</strong><small>Quản lý vận hành</small></div></div><nav aria-label="Điều hướng chính">{navigation.map((item) => { const Icon = icons[item.id] ?? LayoutDashboard; return <button aria-current={currentView === item.id ? "page" : undefined} className={currentView === item.id ? "app-nav__item app-nav__item--active" : "app-nav__item"} key={item.id} onClick={() => onNavigate(item.id)} type="button"><Icon aria-hidden="true" size={18} /><span>{item.label}</span></button>; })}</nav><Button className="app-sidebar__logout" onClick={onLogout} variant="ghost"><LogOut aria-hidden="true" size={17} />Đăng xuất</Button></aside><div className="app-shell__content"><header className="app-header"><div><p>Sports Center</p><strong>{roleLabel}</strong></div><div className="app-header__notifications"><Bell aria-hidden="true" size={18} /><span>{notifications.filter((item) => !item.read_at).length}</span></div></header><main className="app-main">{children}</main>{notifications.length > 0 && <aside className="app-notification-panel" aria-label="Thông báo">{notifications.slice(0, 3).map((item) => <article key={item.id}><strong>{item.title}</strong><p>{item.body}</p>{!item.read_at && <button onClick={() => onReadNotification(item.id)} type="button">Đánh dấu đã đọc</button>}</article>)}</aside>}</div></div>;
}
