const uuid = { type: "string", format: "uuid" };
const nullableUuid = { type: ["string", "null"], format: "uuid" };
const timestamp = { type: "string", format: "date-time" };
const nullableTimestamp = { type: ["string", "null"], format: "date-time" };
const money = {
  type: "string",
  pattern: "^[0-9]+$",
  example: "500000",
  description: "Số tiền VND được trả dưới dạng chuỗi để giữ chính xác số nguyên.",
};
const text = { type: "string" };
const nullableText = { type: ["string", "null"] };
const integer = { type: "integer" };
const ref = (name) => ({ $ref: `#/components/schemas/${name}` });
const array = (items) => ({ type: "array", items });
const record = (properties) => ({ type: "object", properties });

export const serviceSchemas = {
  PublicCourse: record({
    id: uuid,
    name: text,
    description: nullableText,
    priceVnd: money,
    capacity: integer,
    availableSeats: integer,
    sessions: array(record({ name: text, startsAt: timestamp, endsAt: timestamp })),
  }),
  PublicPtPackage: record({
    id: uuid,
    name: text,
    description: nullableText,
    priceVnd: money,
    sessionCount: integer,
    durationDays: integer,
    sessionMinutes: integer,
    cancellationHours: integer,
  }),
  ServiceClassSession: record({
    id: uuid,
    name: text,
    course_id: nullableUuid,
    coach_user_id: uuid,
    room_id: uuid,
    starts_at: timestamp,
    ends_at: timestamp,
    capacity: integer,
    status: text,
  }),
  Course: record({
    id: uuid,
    code: text,
    name: text,
    description: nullableText,
    priceVnd: money,
    price_vnd: money,
    capacity: integer,
    payment_hold_minutes: integer,
    status: { type: "string", enum: ["draft", "published", "cancelled", "completed"] },
    created_at: timestamp,
    updated_at: timestamp,
    reservedSeats: integer,
    sessions: array(ref("ServiceClassSession")),
  }),
  CourseEnrollment: record({
    id: uuid,
    course_id: uuid,
    member_id: uuid,
    priceVnd: money,
    price_vnd_snapshot: money,
    status: { type: "string", enum: ["pending_payment", "active", "cancelled", "completed"] },
    payment_expires_at: nullableTimestamp,
    enrolled_at: timestamp,
    activated_at: nullableTimestamp,
    cancelled_at: nullableTimestamp,
    cancellation_reason: nullableText,
    activation_payment_id: nullableUuid,
    course: ref("Course"),
  }),
  PtPackage: record({
    id: uuid,
    name: text,
    description: nullableText,
    priceVnd: money,
    price_vnd: money,
    session_count: integer,
    duration_days: integer,
    session_minutes: integer,
    cancellation_hours: integer,
    is_active: { type: "boolean" },
    created_at: timestamp,
  }),
  PtAppointment: record({
    id: uuid,
    purchase_id: uuid,
    class_session_id: uuid,
    status: { type: "string", enum: ["scheduled", "completed", "absent", "cancelled"] },
    created_at: timestamp,
    completed_at: nullableTimestamp,
    recorded_by: nullableUuid,
    reason: nullableText,
    session: ref("ServiceClassSession"),
  }),
  PtPurchase: record({
    id: uuid,
    package_id: uuid,
    member_id: uuid,
    package_name_snapshot: text,
    priceVnd: money,
    price_vnd_snapshot: money,
    session_count_snapshot: integer,
    duration_days_snapshot: integer,
    session_minutes_snapshot: integer,
    cancellation_hours_snapshot: integer,
    coach_user_id: nullableUuid,
    status: { type: "string", enum: ["pending_payment", "active", "cancelled", "completed"] },
    purchased_at: timestamp,
    activated_at: nullableTimestamp,
    expires_at: nullableTimestamp,
    activation_payment_id: nullableUuid,
    remainingSessions: integer,
    usedSessions: integer,
    appointments: array(ref("PtAppointment")),
  }),
  PtResources: record({
    rooms: array(record({ id: uuid, name: text })),
    coaches: array(record({ id: uuid, display_name: text })),
  }),
  ServicePayment: record({
    id: uuid,
    transaction_code: text,
    member_id: uuid,
    membership_id: nullableUuid,
    course_enrollment_id: nullableUuid,
    pt_purchase_id: nullableUuid,
    facility_reservation_id: nullableUuid,
    amountVnd: money,
    amount_vnd: money,
    method: { type: "string", enum: ["cash", "bank_transfer", "online"] },
    status: { type: "string", enum: ["pending", "paid", "failed", "refunded"] },
    checkoutUrl: text,
    qrCode: text,
    paid_at: nullableTimestamp,
    fulfillment_error: {
      ...nullableText,
      description: "Có giá trị khi đã thu tiền nhưng chưa cấp được dịch vụ; quản lý cần đối soát.",
    },
  }),
  ServiceRefund: record({
    id: uuid,
    payment_id: uuid,
    member_id: uuid,
    amount_vnd: money,
    amountVnd: money,
    reason: text,
    status: { type: "string", enum: ["pending", "approved", "rejected", "completed"] },
    requested_by: uuid,
    requested_at: timestamp,
    reviewed_by: nullableUuid,
    reviewed_at: nullableTimestamp,
    review_note: nullableText,
    executed_by: nullableUuid,
    executed_at: nullableTimestamp,
    transfer_reference: nullableText,
  }),
};

export function serviceResponse(name, list = false) {
  return {
    type: "object",
    required: ["success", "data"],
    properties: { success: { type: "boolean", const: true }, data: list ? array(ref(name)) : ref(name) },
  };
}
