import { env } from "../config/env.js";

export const openApiSpec = {
  openapi: "3.1.0",
  info: {
    title: "Sports Center API",
    version: "0.1.0",
    description: "API contract for the Sports Center Management System MVP.",
  },
  servers: [{ url: env.apiBasePath }],
  paths: {
    "/members/me": { get: { tags: ["Members"], summary: "Hội viên xem hồ sơ của chính mình", security: [{ sessionCookie: [] }], responses: { 200: { description: "Hồ sơ cá nhân" } } } },
    "/members/{id}/coach-assignments": { get: { tags: ["Coach assignments"], summary: "Lịch sử coach của hội viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Lịch sử" } } }, post: { tags: ["Coach assignments"], summary: "Đổi coach chính và giữ lịch sử hiệu lực", security: [{ sessionCookie: [] }], responses: { 201: { description: "Đã phân công" } } } },
    "/audit-logs": { get: { tags: ["Audit"], summary: "Nhật ký kiểm toán", security: [{ sessionCookie: [] }], responses: { 200: { description: "Nhật ký" } } } },
    "/dashboards/{role}": { get: { tags: ["Dashboard"], summary: "Tổng quan theo vai trò", security: [{ sessionCookie: [] }], responses: { 200: { description: "Chỉ số dashboard" } } } },
    "/notifications": { get: { tags: ["Notifications"], summary: "Thông báo trong hệ thống", security: [{ sessionCookie: [] }], responses: { 200: { description: "Thông báo" } } } },
    "/notifications/{id}/read": { patch: { tags: ["Notifications"], summary: "Đánh dấu đã đọc", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã đọc" } } } },
    "/reports/revenue": { get: { tags: ["Reports"], summary: "Doanh thu theo payment paid_at", security: [{ sessionCookie: [] }], responses: { 200: { description: "Doanh thu" } } } },
    "/reports/attendance": { get: { tags: ["Reports"], summary: "Báo cáo điểm danh", security: [{ sessionCookie: [] }], responses: { 200: { description: "Điểm danh" } } } },
    "/training-templates": { get: { tags: ["Training"], summary: "Mẫu giáo án", security: [{ sessionCookie: [] }], responses: { 200: { description: "Mẫu" } } }, post: { tags: ["Training"], summary: "Tạo mẫu giáo án", security: [{ sessionCookie: [] }], responses: { 201: { description: "Mẫu mới" } } } },
    "/training-plans": { get: { tags: ["Training"], summary: "Danh sách giáo án", security: [{ sessionCookie: [] }], responses: { 200: { description: "Giáo án" } } }, post: { tags: ["Training"], summary: "Tạo giáo án cá nhân", security: [{ sessionCookie: [] }], responses: { 201: { description: "Giáo án mới" } } } },
    "/training-plans/{id}": { patch: { tags: ["Training"], summary: "Cập nhật giáo án", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã cập nhật" } } } },
    "/training-results": { post: { tags: ["Training"], summary: "Ghi nhận kết quả tập", security: [{ sessionCookie: [] }], responses: { 201: { description: "Kết quả mới" } } } },
    "/payments": { get: { tags: ["Payments"], summary: "Danh sách giao dịch", security: [{ sessionCookie: [] }], responses: { 200: { description: "Giao dịch" } } }, post: { tags: ["Payments"], summary: "Tạo giao dịch chờ xác nhận", security: [{ sessionCookie: [] }], responses: { 201: { description: "Giao dịch pending" } } } },
    "/payments/{id}": { get: { tags: ["Payments"], summary: "Chi tiết giao dịch", security: [{ sessionCookie: [] }], responses: { 200: { description: "Giao dịch" } } } },
    "/payments/{id}/confirm": { post: { tags: ["Payments"], summary: "Lễ tân xác nhận tiền mặt/chuyển khoản", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã xác nhận; gói được kích hoạt khi paid" } } } },
    "/payment-providers/{provider}/webhook": { post: { tags: ["Payments"], summary: "Webhook ký HMAC từ VNPay, MoMo hoặc ZaloPay", responses: { 200: { description: "Đã xác nhận giao dịch online" }, 401: { description: "Chữ ký không hợp lệ" } } } },
    "/classes/{id}/attendance": { get: { tags: ["Attendance"], summary: "Danh sách điểm danh lớp", security: [{ sessionCookie: [] }], responses: { 200: { description: "Điểm danh" } } } },
    "/attendance/check-in": { post: { tags: ["Attendance"], summary: "Điểm danh theo booking", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã điểm danh" } } } },
    "/attendance/{id}/check-out": { post: { tags: ["Attendance"], summary: "Check-out theo lượt điểm danh", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Đã check-out" } } } },
    "/attendance/{id}/corrections": { post: { tags: ["Attendance"], summary: "Sửa điểm danh có lý do", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã sửa và audit" } } } },
    "/bookings": { get: { tags: ["Bookings"], summary: "Danh sách đặt chỗ", description: "Hội viên chỉ xem lịch của chính mình; Lễ tân/Quản lý có thể lọc memberId.", security: [{ sessionCookie: [] }], parameters: [{ name: "memberId", in: "query", schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Danh sách booking" }, 403: { description: "Không được xem lịch của hội viên khác" } } }, post: { tags: ["Bookings"], summary: "Đặt chỗ hoặc vào danh sách chờ", description: "Hội viên không cần truyền memberId và không thể đặt thay người khác. Lớp chỉ được đặt một lần khi đang xác nhận/chờ.", security: [{ sessionCookie: [] }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["classId"], properties: { memberId: { type: "string", format: "uuid", description: "Bắt buộc với Lễ tân/Quản lý" }, classId: { type: "string", format: "uuid" } } } } } }, responses: { 201: { description: "Booking confirmed hoặc waitlisted" }, 409: { description: "Đã có booking còn hiệu lực" }, 422: { description: "Lớp không còn mở hoặc gói không đủ điều kiện" } } } },
    "/bookings/{id}/cancel": { patch: { tags: ["Bookings"], summary: "Hủy booking trước giờ học 5 tiếng", description: "Hội viên chỉ hủy booking của chính mình. Khi hủy booking đã xác nhận, hệ thống tự xác nhận người đầu tiên trong danh sách chờ.", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["reason"], properties: { reason: { type: "string", minLength: 3, maxLength: 500 } } } } } }, responses: { 200: { description: "Đã hủy" }, 403: { description: "Không được hủy booking của người khác" }, 422: { description: "Hủy quá muộn" } } } },
    "/classes": { get: { tags: ["Classes"], summary: "Danh sách lớp học", security: [{ sessionCookie: [] }], responses: { 200: { description: "Lớp học" } } }, post: { tags: ["Classes"], summary: "Tạo lớp học nháp", security: [{ sessionCookie: [] }], responses: { 201: { description: "Lớp học mới" } } } },
    "/classes/{id}": { patch: { tags: ["Classes"], summary: "Cập nhật lớp học", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Đã cập nhật" } } } },
    "/classes/{id}/publish": { post: { tags: ["Classes"], summary: "Xuất bản lớp học", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã xuất bản" } } } },
    "/classes/{id}/change-requests": { post: { tags: ["Classes"], summary: "Coach đề xuất hủy hoặc đổi lịch lớp", security: [{ sessionCookie: [] }], responses: { 201: { description: "Yêu cầu chờ lễ tân duyệt" } } } },
    "/class-change-requests/{id}": { patch: { tags: ["Classes"], summary: "Lễ tân duyệt hoặc từ chối thay đổi lớp", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã xử lý booking và thông báo hội viên" } } } },
    "/rooms": { get: { tags: ["Classes"], summary: "Danh sách phòng", security: [{ sessionCookie: [] }], responses: { 200: { description: "Phòng đang hoạt động" } } } },
    "/coaches": { get: { tags: ["Classes"], summary: "Danh sách huấn luyện viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "HLV đang hoạt động" } } } },
    "/membership-packages": { get: { tags: ["Memberships"], summary: "Danh sách gói tập và quyền sử dụng", security: [{ sessionCookie: [] }], responses: { 200: { description: "Gói tập đang cấu hình" } } }, post: { tags: ["Memberships"], summary: "Tạo gói tập", security: [{ sessionCookie: [] }], responses: { 201: { description: "Gói tập mới" } } } },
    "/membership-packages/{id}": { patch: { tags: ["Memberships"], summary: "Cập nhật gói tập", security: [{ sessionCookie: [] }], responses: { 200: { description: "Gói tập đã cập nhật" } } } },
    "/members/me/memberships": { get: { tags: ["Memberships"], summary: "Hội viên xem các gói tập của chính mình", security: [{ sessionCookie: [] }], responses: { 200: { description: "Danh sách gói của tài khoản đăng nhập" } } } },
    "/memberships/{id}/freeze-requests": { post: { tags: ["Memberships"], summary: "Hội viên gửi yêu cầu đóng băng tối đa 3 tháng", description: "Hội viên chỉ có thể yêu cầu cho gói đang hoạt động của chính mình; sau khi Lễ tân duyệt, hệ thống cộng bù đúng số ngày đóng băng.", security: [{ sessionCookie: [] }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["startsOn", "endsOn", "reason"], properties: { startsOn: { type: "string", format: "date" }, endsOn: { type: "string", format: "date" }, reason: { type: "string", minLength: 3, maxLength: 500 } } } } } }, responses: { 201: { description: "Yêu cầu chờ lễ tân duyệt" }, 403: { description: "Không sở hữu gói tập" }, 409: { description: "Đã dùng lượt đóng băng" }, 422: { description: "Không đủ điều kiện hoặc vượt quá 3 tháng" } } } },
    "/membership-freeze-requests/{id}": { patch: { tags: ["Memberships"], summary: "Lễ tân duyệt hoặc từ chối đóng băng", description: "Yêu cầu quyền membership.freeze.review.", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã xử lý" }, 403: { description: "Thiếu quyền duyệt đóng băng" } } } },
    "/memberships/{id}/cancel-pending-renewal": { patch: { tags: ["Memberships"], summary: "Hủy gia hạn đang chờ thanh toán", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã hủy yêu cầu gia hạn" } } } },
    "/members/{id}/memberships": { get: { tags: ["Memberships"], summary: "Lịch sử gói tập của hội viên", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Danh sách membership" } } }, post: { tags: ["Memberships"], summary: "Tạo membership chờ thanh toán", security: [{ sessionCookie: [] }], responses: { 201: { description: "Membership pending_payment" } } } },
    "/members": { get: { tags: ["Members"], summary: "Danh sách hội viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Danh sách hội viên" } } }, post: { tags: ["Members"], summary: "Tạo hồ sơ hội viên", security: [{ sessionCookie: [] }], responses: { 201: { description: "Hồ sơ hội viên mới" } } } },
    "/members/{id}": { get: { tags: ["Members"], summary: "Chi tiết hội viên", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Hội viên" } } }, patch: { tags: ["Members"], summary: "Cập nhật hội viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã cập nhật" } } } },
    "/members/{id}/emergency-contacts": { put: { tags: ["Members"], summary: "Thay thế liên hệ khẩn cấp", security: [{ sessionCookie: [] }], responses: { 200: { description: "Danh sách liên hệ mới" } } } },
    "/staff": { get: { tags: ["Staff"], summary: "Danh sách nhân viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Danh sách nhân sự" }, 403: { description: "Thiếu quyền staff.manage" } } }, post: { tags: ["Staff"], summary: "Tạo nhân viên và trả mật khẩu tạm một lần", security: [{ sessionCookie: [] }], responses: { 201: { description: "Nhân viên mới và temporaryPassword" } } } },
    "/staff/{id}": { get: { tags: ["Staff"], summary: "Chi tiết nhân viên", security: [{ sessionCookie: [] }], parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Nhân viên" } } }, patch: { tags: ["Staff"], summary: "Cập nhật nhân viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã cập nhật" } } } },
    "/staff/{id}/status": { patch: { tags: ["Staff"], summary: "Đình chỉ hoặc kích hoạt nhân viên", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã cập nhật trạng thái" } } } },
    "/auth/register": {
      post: { tags: ["Auth"], summary: "Đăng ký hội viên công khai", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/RegisterRequest" } } } }, responses: { 201: { description: "Đã tạo tài khoản chờ xác thực" }, 409: { description: "Email hoặc số điện thoại đã tồn tại" }, 422: { description: "Dữ liệu không hợp lệ" } } },
    },
    "/auth/verification/confirm": {
      post: { tags: ["Auth"], summary: "Xác thực email hoặc số điện thoại", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/VerificationRequest" } } } }, responses: { 200: { description: "Đã xác thực" }, 422: { description: "Mã không hợp lệ hoặc hết hạn" } } },
    },
    "/auth/verification/resend": { post: { tags: ["Auth"], summary: "Gửi lại mã xác thực", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/VerificationRecipient" } } } }, responses: { 200: { description: "Đã gửi mã" } } } },
    "/auth/login": { post: { tags: ["Auth"], summary: "Đăng nhập", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/LoginRequest" } } } }, responses: { 200: { description: "Đã tạo phiên; cookie HTTP-only được trả về" }, 401: { description: "Sai thông tin đăng nhập" }, 403: { description: "Tài khoản chưa hoạt động" } } } },
    "/auth/logout": { post: { tags: ["Auth"], summary: "Đăng xuất", security: [{ sessionCookie: [] }], responses: { 200: { description: "Đã đăng xuất" }, 401: { description: "Chưa đăng nhập" } } } },
    "/auth/me": { get: { tags: ["Auth"], summary: "Lấy người dùng và quyền của phiên hiện tại", security: [{ sessionCookie: [] }], responses: { 200: { description: "Phiên hợp lệ" }, 401: { description: "Phiên không hợp lệ" } } } },
    "/auth/registrations/pending": { get: { tags: ["Auth"], summary: "Danh sách đăng ký chờ Lễ tân duyệt", security: [{ sessionCookie: [] }], responses: { 200: { description: "Danh sách chờ duyệt" }, 403: { description: "Thiếu quyền registration.approve" } } } },
    "/auth/registrations/{userId}/approve": { post: { tags: ["Auth"], summary: "Lễ tân duyệt tài khoản hội viên", security: [{ sessionCookie: [] }], parameters: [{ name: "userId", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: { description: "Tài khoản đã kích hoạt" }, 403: { description: "Thiếu quyền registration.approve" } } } },
    "/health": {
      get: {
        tags: ["System"],
        summary: "Check API availability",
        responses: {
          200: {
            description: "API is available",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  required: ["success", "data"],
                  properties: {
                    success: { type: "boolean", example: true },
                    data: {
                      type: "object",
                      required: ["status"],
                      properties: { status: { type: "string", example: "ok" } },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
  components: {
    securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "sports_center_session" } },
    schemas: {
      RegisterRequest: { type: "object", required: ["fullName", "email", "phone", "password"], properties: { fullName: { type: "string", example: "Nguyễn Minh Anh" }, email: { type: "string", format: "email" }, phone: { type: "string", example: "0901234567" }, password: { type: "string", format: "password", minLength: 8 } } },
      VerificationRecipient: { type: "object", required: ["userId", "channel"], properties: { userId: { type: "string", format: "uuid" }, channel: { type: "string", enum: ["email", "phone"] } } },
      VerificationRequest: { allOf: [{ $ref: "#/components/schemas/VerificationRecipient" }, { type: "object", required: ["code"], properties: { code: { type: "string", example: "123456" } } }] },
      LoginRequest: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password" } } },
    },
  },
};
