import { randomBytes } from "node:crypto";
import { AppError } from "../../shared/errors/app-error.js";
const viewContact = (contact) => ({ id: contact.id, fullName: contact.full_name, relationship: contact.relationship, phone: contact.phone, isPrimary: contact.is_primary });
const persistContact = (contact) => ({ full_name: contact.fullName, relationship: contact.relationship, phone: contact.phone, is_primary: contact.isPrimary });
const view = ({ member, contacts, overview }) => ({ id: member.id, memberCode: member.member_code, fullName: member.full_name, email: member.email, phone: member.phone, dateOfBirth: member.date_of_birth, gender: member.gender, joinedAt: member.joined_at, contacts: (contacts ?? []).map(viewContact), coachName: overview?.coachName ?? null, registeredPackageName: overview?.membership?.package_name_snapshot ?? null, membershipStatus: overview?.membership?.status ?? null, membershipExpiresOn: overview?.membership?.expires_on ?? null });
export function createMemberService({ repository, auditService }) { return {
  async list() { return Promise.all((await repository.listWithOverview()).map(async ({ member, overview }) => view({ member, overview, contacts: await repository.contacts(member.id) }))); },
  async get(id) { const item = await repository.findWithContacts(id); if (!item) throw new AppError({ statusCode: 404, code: "MEMBER_NOT_FOUND", message: "Không tìm thấy hội viên." }); return view(item); },
  async getByUserId(userId) { const member = await repository.findByUserId(userId); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_PROFILE_NOT_FOUND", message: "Tài khoản chưa có hồ sơ hội viên." }); return this.get(member.id); },
  async create(input, actorUserId) { const code = `MBR-${randomBytes(5).toString("hex").toUpperCase()}`; try { const created = await repository.create({ member_code: code, full_name: input.fullName, email: input.email ?? null, phone: input.phone, date_of_birth: input.dateOfBirth ? new Date(input.dateOfBirth) : null, gender: input.gender ?? null, created_by: actorUserId, contacts: input.contacts.map(persistContact) }); await auditService.record({ actorUserId, action: "member.created", entityType: "member", entityId: created.member.id, summary: "Đã tạo hồ sơ hội viên." }); return view(created); } catch (error) { if (error.code === "P2002") throw new AppError({ statusCode: 409, code: "MEMBER_CONTACT_EXISTS", message: "Email hoặc số điện thoại đã được sử dụng." }); throw error; } },
  async update(id, input, actorUserId) { await this.get(id); const updated = await repository.update(id, { ...(input.fullName ? { full_name: input.fullName } : {}), ...(input.email !== undefined ? { email: input.email } : {}), ...(input.phone ? { phone: input.phone } : {}), ...(input.dateOfBirth !== undefined ? { date_of_birth: input.dateOfBirth ? new Date(input.dateOfBirth) : null } : {}), ...(input.gender !== undefined ? { gender: input.gender } : {}) }); await auditService.record({ actorUserId, action: "member.updated", entityType: "member", entityId: id, summary: "Đã cập nhật hồ sơ hội viên." }); return view(updated); },
  async replaceContacts(id, contacts, actorUserId) { await this.get(id); if (contacts.filter((item) => item.isPrimary).length > 1) throw new AppError({ statusCode: 422, code: "MULTIPLE_PRIMARY_CONTACTS", message: "Chỉ được có một liên hệ khẩn cấp chính." }); const updated = await repository.replaceContacts(id, contacts.map(persistContact)); await auditService.record({ actorUserId, action: "member.emergency_contacts.updated", entityType: "member", entityId: id, summary: "Đã cập nhật liên hệ khẩn cấp." }); return updated.map(viewContact); },
}; }
