import { AppError } from "../../shared/errors/app-error.js";
import { violatesUniqueConstraint } from "../../shared/database/unique-constraint.js";

const viewPackage = (item, entitlements) => ({ id: item.id, code: item.code, name: item.name, priceVnd: item.price_vnd.toString(), durationDays: item.duration_days, tierRank: item.tier_rank, benefits: item.benefits, isActive: item.is_active, entitlements });
const viewMembership = ({ price_vnd_snapshot, ...membership }) => ({ ...membership, priceVnd: price_vnd_snapshot.toString() });
const daysBetween = (from, to) => Math.ceil((Date.UTC(to.getUTCFullYear(), to.getUTCMonth(), to.getUTCDate()) - Date.UTC(from.getUTCFullYear(), from.getUTCMonth(), from.getUTCDate())) / 86400000);
const packageConflict = (error) => {
  if (!violatesUniqueConstraint(error)) return null;
  if (violatesUniqueConstraint(error, ["code"])) return new AppError({ statusCode: 409, code: "MEMBERSHIP_PACKAGE_CODE_EXISTS", message: "Mã gói tập này đã tồn tại. Vui lòng dùng mã khác.", details: { field: "code" } });
  if (violatesUniqueConstraint(error, ["name"])) return new AppError({ statusCode: 409, code: "MEMBERSHIP_PACKAGE_NAME_EXISTS", message: "Tên gói tập này đã tồn tại. Vui lòng dùng tên khác.", details: { field: "name" } });
  if (violatesUniqueConstraint(error, ["tier_rank"])) return new AppError({ statusCode: 409, code: "MEMBERSHIP_PACKAGE_TIER_EXISTS", message: "Thứ hạng quyền này đã được dùng bởi một gói khác. Vui lòng chọn thứ hạng khác.", details: { field: "tierRank" } });
  return new AppError({ statusCode: 409, code: "MEMBERSHIP_PACKAGE_EXISTS", message: "Thông tin gói tập đã tồn tại. Vui lòng kiểm tra lại." });
};
export function createMembershipService({ repository, auditService }) { async function listPackages() { const items = await repository.packages(); const direct = await Promise.all(items.map((item) => repository.entitlements(item.id))); return items.map((item, index) => viewPackage(item, [...new Map(direct.slice(0, index + 1).flat().map((entitlement) => [entitlement.entitlement, entitlement])).values()])); } async function ownedMemberId(actor) { const member = await repository.memberByUser(actor.id); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_PROFILE_NOT_FOUND", message: "Không tìm thấy hồ sơ hội viên của tài khoản này." }); return member.id; }
  return { listPackages,
    async listPublicPackages() {
      return (await repository.publicPackages()).map((item) => ({
        code: item.code,
        name: item.name,
        priceVnd: item.price_vnd.toString(),
        durationDays: item.duration_days,
        benefits: Array.isArray(item.benefits) ? item.benefits.filter((benefit) => typeof benefit === "string") : [],
      }));
    },
    async createPackage(input, actorUserId) { try { const item = await repository.createPackage({ code: input.code, name: input.name, price_vnd: BigInt(input.priceVnd), duration_days: input.durationDays, tier_rank: input.tierRank, benefits: input.benefits ?? [], is_active: input.isActive ?? true }); await repository.replaceEntitlements(item.id, input.entitlements ?? []); await auditService.record({ actorUserId, action: "membership_package.created", entityType: "membership_package", entityId: item.id, summary: "Đã tạo gói tập." }); return viewPackage(item, await repository.entitlements(item.id)); } catch (error) { throw packageConflict(error) ?? error; } },
    async updatePackage(id, input, actorUserId) { if (!await repository.packageById(id)) throw new AppError({ statusCode: 404, code: "MEMBERSHIP_PACKAGE_NOT_FOUND", message: "Không tìm thấy gói tập." }); try { const item = await repository.updatePackage(id, { ...(input.name !== undefined && { name: input.name }), ...(input.priceVnd !== undefined && { price_vnd: BigInt(input.priceVnd) }), ...(input.durationDays !== undefined && { duration_days: input.durationDays }), ...(input.tierRank !== undefined && { tier_rank: input.tierRank }), ...(input.benefits !== undefined && { benefits: input.benefits }), ...(input.isActive !== undefined && { is_active: input.isActive }) }); if (input.entitlements) await repository.replaceEntitlements(id, input.entitlements); await auditService.record({ actorUserId, action: "membership_package.updated", entityType: "membership_package", entityId: id, summary: "Đã cập nhật gói tập." }); return viewPackage(item, await repository.entitlements(id)); } catch (error) { throw packageConflict(error) ?? error; } },
    async createMemberMembership(input, actorUserId) { if (!await repository.memberExists(input.memberId)) throw new AppError({ statusCode: 404, code: "MEMBER_NOT_FOUND", message: "Không tìm thấy hội viên." }); const pkg = await repository.packageById(input.packageId); if (!pkg || !pkg.is_active) throw new AppError({ statusCode: 422, code: "MEMBERSHIP_PACKAGE_UNAVAILABLE", message: "Gói tập không khả dụng." }); const startsOn = new Date(input.startsOn); const expiresOn = new Date(startsOn); expiresOn.setUTCDate(expiresOn.getUTCDate() + pkg.duration_days); const isFree = pkg.price_vnd === 0n; const membership = await repository.createMembership({ member_id: input.memberId, package_id: pkg.id, package_name_snapshot: pkg.name, price_vnd_snapshot: pkg.price_vnd, starts_on: startsOn, expires_on: expiresOn, created_by: actorUserId, ...(isFree ? { status: "active", activated_at: new Date() } : {}) }); await auditService.record({ actorUserId, action: isFree ? "membership.free_activated" : "membership.created", entityType: "membership", entityId: membership.id, summary: isFree ? "Đã kích hoạt gói miễn phí, không cần thanh toán." : "Đã tạo gói tập chờ thanh toán." }); return viewMembership(membership); },
    async listMemberMemberships(memberId) { if (!await repository.memberExists(memberId)) throw new AppError({ statusCode: 404, code: "MEMBER_NOT_FOUND", message: "Không tìm thấy hội viên." }); return (await repository.memberships(memberId)).map(viewMembership); },
    async listOwnMemberships(actor) { return this.listMemberMemberships(await ownedMemberId(actor)); },
    async requestFreeze(membershipId, input, actor) { const membership = await repository.membership(membershipId); if (!membership || membership.status !== "active") throw new AppError({ statusCode: 422, code: "FREEZE_NOT_ELIGIBLE", message: "Chỉ gói đang hoạt động mới có thể yêu cầu đóng băng." }); if (actor.role === "member" && membership.member_id !== await ownedMemberId(actor)) throw new AppError({ statusCode: 403, code: "FREEZE_ACCESS_DENIED", message: "Bạn chỉ có thể gửi yêu cầu đóng băng gói của mình." }); if ((await repository.freezeRequests(membershipId)).some((item) => item.status !== "rejected")) throw new AppError({ statusCode: 409, code: "FREEZE_LIMIT_REACHED", message: "Mỗi gói chỉ được yêu cầu đóng băng một lần." }); const startsOn = new Date(input.startsOn); const endsOn = new Date(input.endsOn); const today = new Date(); today.setUTCHours(0, 0, 0, 0); const days = daysBetween(startsOn, endsOn); if (startsOn < today || endsOn > membership.expires_on || days < 1 || days > 92) throw new AppError({ statusCode: 422, code: "FREEZE_DURATION_INVALID", message: "Thời gian đóng băng phải trong hiệu lực gói, từ hôm nay đến tối đa 3 tháng." }); const request = await repository.createFreeze({ membership_id: membershipId, requested_by: actor.id, starts_on: startsOn, ends_on: endsOn, reason: input.reason }); await auditService.record({ actorUserId: actor.id, action: "membership.freeze_requested", entityType: "membership", entityId: membershipId, summary: "Đã gửi yêu cầu đóng băng gói tập.", reason: input.reason }); return request; },
    freezeRequests: (status) => repository.reviewQueue(status),
    async reviewFreeze(requestId, approved, actorUserId) { const request = await repository.freezeRequest(requestId); if (!request || request.status !== "pending") throw new AppError({ statusCode: 422, code: "FREEZE_REQUEST_UNAVAILABLE", message: "Yêu cầu đóng băng không còn chờ duyệt." }); let result; if (approved) { const membership = await repository.membership(request.membership_id); if (!membership || !["active", "expiring_soon"].includes(membership.status)) throw new AppError({ statusCode: 422, code: "FREEZE_NOT_ELIGIBLE", message: "Gói tập không còn đủ điều kiện để đóng băng." }); const days = daysBetween(request.starts_on, request.ends_on); const expiresOn = new Date(membership.expires_on); expiresOn.setUTCDate(expiresOn.getUTCDate() + days); await repository.extendForFreeze(request.membership_id, expiresOn, days); result = await repository.approveFreeze(requestId, actorUserId); await repository.notifyMember(request.membership_id, "Yêu cầu đóng băng đã được duyệt", "Gói tập sẽ được đóng băng theo khoảng thời gian đã đăng ký và hạn dùng đã được cộng bù."); } else { result = await repository.rejectFreeze(requestId, actorUserId); await repository.notifyMember(request.membership_id, "Yêu cầu đóng băng bị từ chối", "Lễ tân chưa phê duyệt yêu cầu đóng băng gói tập của bạn."); } await auditService.record({ actorUserId, action: approved ? "membership.freeze_approved" : "membership.freeze_rejected", entityType: "membership", entityId: request.membership_id, summary: approved ? "Đã duyệt đóng băng và cộng bù thời hạn." : "Đã từ chối đóng băng." }); return result; },
    async cancelPendingRenewal(id, actorUserId) { const membership = await repository.membership(id); if (!membership || membership.status !== "pending_payment") throw new AppError({ statusCode: 422, code: "RENEWAL_CANCELLATION_NOT_ELIGIBLE", message: "Chỉ hủy được yêu cầu gia hạn đang chờ thanh toán." }); const result = await repository.cancelPendingRenewal(id); await auditService.record({ actorUserId, action: "membership.pending_renewal_cancelled", entityType: "membership", entityId: id, summary: "Đã hủy yêu cầu gia hạn chờ thanh toán." }); return result; },
  }; }
