import { useCallback, useEffect, useState } from "react";
import { Button } from "../../components/ui/Button.jsx";
import { membershipApi } from "./membership-api.js";
import "../members/members.css";

const emptyPackage = { code: "", name: "", priceVnd: "", durationDays: "30", tierRank: "", benefits: "" };
const emptyFreeze = { membershipId: "", startsOn: "", endsOn: "", reason: "" };
const membershipStatus = { pending_payment: "Chờ thanh toán", active: "Đang hoạt động", expiring_soon: "Sắp hết hạn", expired: "Đã hết hạn", frozen: "Đang đóng băng", cancelled: "Đã hủy" };

export function MembershipsPage({ session }) {
  const isMember = session?.user.role === "member";
  const [packages, setPackages] = useState([]); const [memberships, setMemberships] = useState([]);
  const [packageForm, setPackageForm] = useState(emptyPackage); const [freezeForm, setFreezeForm] = useState(emptyFreeze);
  const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setError(""); try { if (isMember) setMemberships(await membershipApi.mine()); else setPackages(await membershipApi.packages()); } catch (caught) { setError(caught.message); } }, [isMember]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function createPackage(event) { event.preventDefault(); setError(""); try { await membershipApi.createPackage({ ...packageForm, priceVnd: Number(packageForm.priceVnd), durationDays: Number(packageForm.durationDays), tierRank: Number(packageForm.tierRank), benefits: packageForm.benefits.split("\n").filter(Boolean) }); setPackageForm(emptyPackage); setNotice("Đã tạo gói tập."); await load(); } catch (caught) { setError(caught.message); } }
  async function requestFreeze(event) { event.preventDefault(); setError(""); try { await membershipApi.requestFreeze(freezeForm.membershipId, { startsOn: freezeForm.startsOn, endsOn: freezeForm.endsOn, reason: freezeForm.reason }); setFreezeForm(emptyFreeze); setNotice("Đã gửi yêu cầu đóng băng để Lễ tân duyệt."); await load(); } catch (caught) { setError(caught.message); } }
  if (isMember) return <main className="members-page"><header><p>Gói tập</p><h1>Gói tập của tôi</h1></header>{error && <p className="auth-alert" role="alert">{error}</p>}{notice && <p className="auth-success" role="status">{notice}</p>}<section className="members-grid"><form className="members-form" onSubmit={requestFreeze}><h2>Yêu cầu đóng băng</h2><label>Gói tập<select value={freezeForm.membershipId} onChange={(event) => setFreezeForm({ ...freezeForm, membershipId: event.target.value })} required><option value="">Chọn gói đang hoạt động</option>{memberships.filter((item) => item.status === "active").map((item) => <option value={item.id} key={item.id}>{item.package_name_snapshot} — hết hạn {new Date(item.expires_on).toLocaleDateString("vi-VN")}</option>)}</select></label><label>Ngày bắt đầu<input type="date" value={freezeForm.startsOn} onChange={(event) => setFreezeForm({ ...freezeForm, startsOn: event.target.value })} required /></label><label>Ngày kết thúc<input type="date" value={freezeForm.endsOn} onChange={(event) => setFreezeForm({ ...freezeForm, endsOn: event.target.value })} required /></label><label>Lý do<textarea value={freezeForm.reason} onChange={(event) => setFreezeForm({ ...freezeForm, reason: event.target.value })} required /></label><p className="form-helper">Tối đa một lần cho mỗi gói, không quá 3 tháng. Sau khi duyệt, hạn gói được cộng bù đúng số ngày đóng băng.</p><Button type="submit">Gửi yêu cầu</Button></form><section className="members-list"><h2>Danh sách gói</h2>{memberships.length === 0 ? <p>Chưa có gói tập.</p> : <div className="table-scroll"><table><thead><tr><th>Gói</th><th>Hiệu lực</th><th>Trạng thái</th></tr></thead><tbody>{memberships.map((item) => <tr key={item.id}><td><strong>{item.package_name_snapshot}</strong><small>{Number(item.priceVnd).toLocaleString("vi-VN")} ₫</small></td><td>{new Date(item.starts_on).toLocaleDateString("vi-VN")} – {new Date(item.expires_on).toLocaleDateString("vi-VN")}</td><td>{membershipStatus[item.status] ?? item.status}</td></tr>)}</tbody></table></div>}</section></section></main>;
  return <main className="members-page"><header><p>Gói tập</p><h1>Gói tập và quyền sử dụng</h1></header>{error && <p className="auth-alert">{error}</p>}{notice && <p className="auth-success">{notice}</p>}<div className="members-grid"><form className="members-form" onSubmit={createPackage}><h2>Tạo gói tập</h2>{[["code", "Mã gói"], ["name", "Tên gói"], ["priceVnd", "Giá (VNĐ)"], ["durationDays", "Số ngày"], ["tierRank", "Thứ hạng quyền"]].map(([key, label]) => <label key={key}>{label}<input value={packageForm[key]} onChange={(event) => setPackageForm({ ...packageForm, [key]: event.target.value })} required /></label>)}<label>Quyền hiển thị (mỗi dòng một quyền)<textarea value={packageForm.benefits} onChange={(event) => setPackageForm({ ...packageForm, benefits: event.target.value })} /></label><Button type="submit">Tạo gói</Button></form><section className="members-list"><h2>Danh mục gói</h2><p>Gói hạng cao tự động kế thừa quyền của toàn bộ gói hạng thấp hơn.</p><div className="table-scroll"><table><thead><tr><th>Gói</th><th>Thời hạn</th><th>Giá</th><th>Quyền sử dụng</th></tr></thead><tbody>{packages.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code} · Hạng {item.tierRank}</small></td><td>{item.durationDays} ngày</td><td>{Number(item.priceVnd).toLocaleString("vi-VN")} ₫</td><td>{item.entitlements.map((x) => x.entitlement).join(", ")}</td></tr>)}</tbody></table></div></section></div></main>;
}
