import { useCallback, useEffect, useState } from "react";
import { Button } from "../../components/ui/Button.jsx";
import { memberApi } from "../members/member-api.js";
import { membershipApi } from "./membership-api.js";
import "../members/members.css";

const emptyPackage = { code: "", name: "", priceVnd: "", durationDays: "30", tierRank: "", benefits: "", entitlements: [] };
const emptyFreeze = { membershipId: "", startsOn: "", endsOn: "", reason: "" };
const emptyMembership = { memberId: "", packageId: "", startsOn: new Date().toISOString().slice(0, 10) };
const membershipStatus = { pending_payment: "Chờ thanh toán", active: "Đang hoạt động", expiring_soon: "Sắp hết hạn", expired: "Đã hết hạn", frozen: "Đang đóng băng", cancelled: "Đã hủy" };
const entitlementLabels = { gym_access: "Tập gym", group_class_booking: "Đặt lớp nhóm", pool_access: "Hồ bơi", sauna_access: "Xông hơi", towel_service: "Khăn tập", premium_locker: "Tủ đồ cao cấp", pt_session: "Buổi tập với PT" };

export function MembershipsPage({ session }) {
  const role = session?.user?.role;
  const isMember = role === "member";
  const canCreatePackages = role === "manager";
  const [packages, setPackages] = useState([]); const [members, setMembers] = useState([]); const [memberships, setMemberships] = useState([]);
  const [packageForm, setPackageForm] = useState(emptyPackage); const [freezeForm, setFreezeForm] = useState(emptyFreeze); const [membershipForm, setMembershipForm] = useState(emptyMembership);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => {
    setError(""); setLoading(true);
    try {
      if (isMember) setMemberships(await membershipApi.mine());
      else { const [nextPackages, nextMembers] = await Promise.all([membershipApi.packages(), memberApi.list()]); setPackages(nextPackages); setMembers(nextMembers); }
    } catch (caught) { setError(caught.message); }
    finally { setLoading(false); }
  }, [isMember]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);

  async function createPackage(event) { event.preventDefault(); setError(""); setNotice(""); setSubmitting(true); try { await membershipApi.createPackage({ ...packageForm, priceVnd: Number(packageForm.priceVnd), durationDays: Number(packageForm.durationDays), tierRank: Number(packageForm.tierRank), benefits: packageForm.benefits.split("\n").map((value) => value.trim()).filter(Boolean), entitlements: packageForm.entitlements.map((code) => ({ code })) }); setPackageForm(emptyPackage); setNotice("Đã tạo gói tập."); await load(); } catch (caught) { setError(caught.message); } finally { setSubmitting(false); } }
  function toggleEntitlement(code) { setPackageForm((value) => ({ ...value, entitlements: value.entitlements.includes(code) ? value.entitlements.filter((item) => item !== code) : [...value.entitlements, code] })); }
  async function createMembership(event) { event.preventDefault(); setError(""); setNotice(""); setSubmitting(true); try { await membershipApi.create(membershipForm.memberId, { packageId: membershipForm.packageId, startsOn: membershipForm.startsOn }); setMembershipForm(emptyMembership); setNotice("Đã tạo gói chờ thanh toán. Hãy chuyển sang Thanh toán để ghi nhận giao dịch."); } catch (caught) { setError(caught.message); } finally { setSubmitting(false); } }
  async function requestFreeze(event) { event.preventDefault(); setError(""); setNotice(""); setSubmitting(true); try { await membershipApi.requestFreeze(freezeForm.membershipId, { startsOn: freezeForm.startsOn, endsOn: freezeForm.endsOn, reason: freezeForm.reason }); setFreezeForm(emptyFreeze); setNotice("Đã gửi yêu cầu đóng băng để Lễ tân duyệt."); await load(); } catch (caught) { setError(caught.message); } finally { setSubmitting(false); } }

  if (isMember) return <main className="members-page"><header><p>Gói tập</p><h1>Gói tập của tôi</h1></header>{error && <p className="auth-alert" role="alert">{error}</p>}{notice && <p className="auth-success" role="status">{notice}</p>}<section className="members-grid"><form className="members-form" onSubmit={requestFreeze}><h2>Yêu cầu đóng băng</h2><label>Gói tập<select onChange={(event) => setFreezeForm({ ...freezeForm, membershipId: event.target.value })} required value={freezeForm.membershipId}><option value="">Chọn gói đang hoạt động</option>{memberships.filter((item) => item.status === "active").map((item) => <option key={item.id} value={item.id}>{item.package_name_snapshot} — hết hạn {new Date(item.expires_on).toLocaleDateString("vi-VN")}</option>)}</select></label><label>Ngày bắt đầu<input onChange={(event) => setFreezeForm({ ...freezeForm, startsOn: event.target.value })} required type="date" value={freezeForm.startsOn} /></label><label>Ngày kết thúc<input onChange={(event) => setFreezeForm({ ...freezeForm, endsOn: event.target.value })} required type="date" value={freezeForm.endsOn} /></label><label>Lý do<textarea minLength="3" onChange={(event) => setFreezeForm({ ...freezeForm, reason: event.target.value })} required value={freezeForm.reason} /></label><p className="form-helper">Tối đa một lần cho mỗi gói, không quá 3 tháng. Sau khi duyệt, hạn gói được cộng bù đúng số ngày đóng băng.</p><Button loading={submitting} type="submit">Gửi yêu cầu</Button></form><MembershipList items={memberships} loading={loading} /></section></main>;

  return <main className="members-page"><header><p>Gói tập</p><h1>Gói tập và quyền sử dụng</h1></header>{error && <p className="auth-alert" role="alert">{error}</p>}{notice && <p className="auth-success" role="status">{notice}</p>}<div className="members-grid">{canCreatePackages ? <form className="members-form" onSubmit={createPackage}><h2>Tạo gói tập</h2>{[["code", "Mã gói"], ["name", "Tên gói"], ["priceVnd", "Giá (VNĐ)"], ["durationDays", "Số ngày"], ["tierRank", "Thứ hạng quyền"]].map(([key, label]) => <label key={key}>{label}<input onChange={(event) => setPackageForm({ ...packageForm, [key]: event.target.value })} required value={packageForm[key]} /></label>)}<fieldset className="entitlement-fieldset"><legend>Quyền sử dụng</legend>{Object.entries(entitlementLabels).map(([code, label]) => <label key={code}><input checked={packageForm.entitlements.includes(code)} onChange={() => toggleEntitlement(code)} type="checkbox" />{label}</label>)}</fieldset><label>Quyền hiển thị (mỗi dòng một quyền)<textarea onChange={(event) => setPackageForm({ ...packageForm, benefits: event.target.value })} value={packageForm.benefits} /></label><Button loading={submitting} type="submit">Tạo gói</Button></form> : <section className="members-form"><h2>Quyền gói tập</h2><p>Quản lý cấu hình giá và quyền. Lễ tân tạo gói cho hội viên và ghi nhận thanh toán.</p></section>}
    <form className="members-form" onSubmit={createMembership}><h2>Tạo gói cho hội viên</h2><label>Hội viên<select onChange={(event) => setMembershipForm({ ...membershipForm, memberId: event.target.value })} required value={membershipForm.memberId}><option value="">Chọn hội viên</option>{members.map((member) => <option key={member.id} value={member.id}>{member.fullName} — {member.memberCode}</option>)}</select></label><label>Gói tập<select onChange={(event) => setMembershipForm({ ...membershipForm, packageId: event.target.value })} required value={membershipForm.packageId}><option value="">Chọn gói</option>{packages.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.name} — {Number(item.priceVnd).toLocaleString("vi-VN")} ₫</option>)}</select></label><label>Ngày bắt đầu dự kiến<input onChange={(event) => setMembershipForm({ ...membershipForm, startsOn: event.target.value })} required type="date" value={membershipForm.startsOn} /></label><p className="form-helper">Membership chỉ được kích hoạt sau giao dịch thanh toán thành công.</p><Button loading={submitting} type="submit">Tạo chờ thanh toán</Button></form>
  </div><section className="members-list"><div className="list-heading"><h2>Danh mục gói</h2><Button onClick={load} size="sm" variant="ghost">Tải lại</Button></div><p>Gói hạng cao tự động kế thừa quyền của toàn bộ gói hạng thấp hơn.</p>{loading ? <p>Đang tải…</p> : <div className="table-scroll"><table><thead><tr><th>Gói</th><th>Thời hạn</th><th>Giá</th><th>Quyền sử dụng</th></tr></thead><tbody>{packages.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code} · Hạng {item.tierRank}</small></td><td>{item.durationDays} ngày</td><td>{Number(item.priceVnd).toLocaleString("vi-VN")} ₫</td><td>{item.entitlements.map((x) => x.entitlement).join(", ") || item.benefits.join(", ") || "Chưa cấu hình"}</td></tr>)}</tbody></table></div>}</section></main>;
}

function MembershipList({ items, loading }) { return <section className="members-list"><h2>Danh sách gói</h2>{loading ? <p>Đang tải…</p> : items.length === 0 ? <p>Chưa có gói tập.</p> : <div className="table-scroll"><table><thead><tr><th>Gói</th><th>Hiệu lực</th><th>Trạng thái</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.package_name_snapshot}</strong><small>{Number(item.priceVnd).toLocaleString("vi-VN")} ₫</small></td><td>{new Date(item.starts_on).toLocaleDateString("vi-VN")} – {new Date(item.expires_on).toLocaleDateString("vi-VN")}</td><td>{membershipStatus[item.status] ?? item.status}</td></tr>)}</tbody></table></div>}</section>; }
