import { LogOut } from "lucide-react";
import { useState } from "react";
import { Button } from "../../components/ui/Button.jsx";
import { authApi } from "./auth-api.js";
import { StaffPage } from "../staff/StaffPage.jsx";
import { MembersPage } from "../members/MembersPage.jsx";
import { MembershipsPage } from "../memberships/MembershipsPage.jsx";
import { ClassesPage } from "../classes/ClassesPage.jsx";
const labels = { manager: "Quản lý trung tâm", receptionist: "Lễ tân", coach: "Huấn luyện viên", member: "Hội viên" };
export function DashboardPlaceholder({ session, onLogout }) { const [view, setView] = useState("dashboard"); async function logout() { await authApi.logout(); onLogout(); } if (view === "staff") return <><StaffPage /><button className="staff-back" onClick={() => setView("dashboard")}>← Tổng quan</button></>; if (view === "members") return <><MembersPage /><button className="staff-back" onClick={() => setView("dashboard")}>← Tổng quan</button></>; if (view === "packages") return <><MembershipsPage /><button className="staff-back" onClick={() => setView("dashboard")}>← Tổng quan</button></>; if (view === "classes") return <><ClassesPage /><button className="staff-back" onClick={() => setView("dashboard")}>← Tổng quan</button></>; return <main className="dashboard-placeholder"><header><div><p>Sports Center</p><h1>{labels[session.user.role] ?? "Tổng quan"}</h1></div><Button variant="secondary" onClick={logout}><LogOut size={16} aria-hidden="true" />Đăng xuất</Button></header><section><h2>Đăng nhập thành công</h2><p>Khung dashboard dành cho {labels[session.user.role] ?? session.user.role} đã sẵn sàng.</p>{session.user.role === "manager" && <><Button onClick={() => setView("staff")}>Quản lý nhân viên</Button><Button variant="secondary" onClick={() => setView("members")}>Quản lý hội viên</Button><Button variant="secondary" onClick={() => setView("packages")}>Gói tập</Button><Button variant="secondary" onClick={() => setView("classes")}>Lớp học</Button></>}</section></main>; }
