import { useState } from "react";
import { UserPlus } from "lucide-react";
import { ApiError } from "../../api/api-error.js";
import { Button } from "../../components/ui/Button.jsx";
import { authApi } from "./auth-api.js";
import { AuthLayout } from "./AuthLayout.jsx";

export function RegisterPage({ onLogin, onRegistered }) {
  const [input, setInput] = useState({ fullName: "", email: "", phone: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = (event) => setInput((current) => ({ ...current, [event.target.name]: event.target.value }));
  async function submit(event) { event.preventDefault(); setError(""); setLoading(true); try { const registration = await authApi.register(input); onRegistered({ userId: registration.user.id, channels: registration.verifications.map(({ channel }) => channel), developmentCodes: Object.fromEntries(registration.verifications.filter((item) => item.developmentCode).map((item) => [item.channel, item.developmentCode])) }); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Không thể tạo tài khoản."); } finally { setLoading(false); } }
  return <AuthLayout><div className="auth-card"><h2>Tạo tài khoản hội viên</h2><p className="auth-card__subtitle">Xác thực email, sau đó chờ Lễ tân duyệt.</p><form className="auth-form" onSubmit={submit}><div className="field"><label htmlFor="register-name">Họ và tên</label><input id="register-name" name="fullName" value={input.fullName} onChange={update} autoComplete="name" required minLength="2" /></div><div className="field"><label htmlFor="register-email">Email</label><input id="register-email" name="email" value={input.email} onChange={update} type="email" autoComplete="email" required /></div><div className="field"><label htmlFor="register-phone">Số điện thoại</label><input id="register-phone" name="phone" value={input.phone} onChange={update} type="tel" inputMode="tel" autoComplete="tel" placeholder="0901234567" required /></div><div className="field"><label htmlFor="register-password">Mật khẩu</label><input id="register-password" name="password" value={input.password} onChange={update} type="password" autoComplete="new-password" minLength="8" required /><small>Ít nhất 8 ký tự, gồm chữ hoa, chữ thường và số.</small></div>{error && <p className="auth-alert" role="alert">{error}</p>}<Button type="submit" size="lg" loading={loading}><UserPlus size={17} aria-hidden="true" />Đăng ký</Button></form><p className="auth-note">Đã có tài khoản? <button className="auth-link" type="button" onClick={onLogin}>Đăng nhập</button></p></div></AuthLayout>;
}
