import { useState } from "react";
import { Button } from "../../../../shared/ui/Button.jsx";
import { Dialog } from "../../../../shared/ui/Dialog.jsx";

export function MemberEditorDialog({ detail, loading, memberId, onClose, onSubmit }) {
  const close = () => { if (!loading) onClose(); };
  return <Dialog isOpen={Boolean(memberId)} onClose={close} title="Cập nhật hội viên"><div className="dialog__body">{loading && !detail ? <p>Đang tải hồ sơ…</p> : detail && <MemberEditorForm detail={detail} loading={loading} onSubmit={onSubmit} />}</div><div className="dialog__actions"><Button disabled={loading} onClick={close} type="button" variant="secondary">Hủy</Button><Button disabled={!detail} form="member-editor-form" loading={loading} type="submit">Lưu thay đổi</Button></div></Dialog>;
}

function MemberEditorForm({ detail, loading, onSubmit }) {
  const [form, setForm] = useState({ fullName: detail.fullName, email: detail.email ?? "", phone: detail.phone, contacts: detail.contacts ?? [] });
  const updateContact = (index, key, value) => setForm((current) => ({ ...current, contacts: current.contacts.map((contact, position) => position === index ? { ...contact, [key]: value } : key === "isPrimary" && value ? { ...contact, isPrimary: false } : contact) }));
  const addContact = () => setForm((current) => ({ ...current, contacts: [...current.contacts, { fullName: "", relationship: "", phone: "", isPrimary: current.contacts.length === 0 }] }));
  return <form id="member-editor-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}><label>Họ tên<input disabled={loading} onChange={(event) => setForm((current) => ({ ...current, fullName: event.target.value }))} required value={form.fullName} /></label><label>Email<input disabled={loading} onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))} type="email" value={form.email} /></label><label>Số điện thoại<input disabled={loading} onChange={(event) => setForm((current) => ({ ...current, phone: event.target.value }))} required value={form.phone} /></label><section className="assignment-history"><h3>Liên hệ khẩn cấp</h3>{form.contacts.map((contact, index) => <div className="dialog__body" key={index}><label>Họ tên<input disabled={loading} onChange={(event) => updateContact(index, "fullName", event.target.value)} required value={contact.fullName} /></label><label>Quan hệ<input disabled={loading} onChange={(event) => updateContact(index, "relationship", event.target.value)} required value={contact.relationship} /></label><label>Số điện thoại<input disabled={loading} onChange={(event) => updateContact(index, "phone", event.target.value)} required value={contact.phone} /></label><label><input checked={contact.isPrimary} disabled={loading} onChange={(event) => updateContact(index, "isPrimary", event.target.checked)} type="checkbox" /> Liên hệ chính</label></div>)}{form.contacts.length < 3 && <Button disabled={loading} onClick={addContact} size="sm" type="button" variant="secondary">Thêm liên hệ</Button>}</section></form>;
}
