import { randomBytes } from "node:crypto";
import { AppError } from "../../shared/errors/app-error.js";
import { sandboxPaymentUrl, verifySandboxCallback } from "./payment-gateway.js";
const output = (payment) => ({ ...payment, amountVnd: payment.amount_vnd.toString(), member: payment.member ? { id: payment.member.id, fullName: payment.member.full_name, memberCode: payment.member.member_code, phone: payment.member.phone, email: payment.member.email } : null, membership: payment.membership ? { id: payment.membership.id, packageName: payment.membership.package_name_snapshot, status: payment.membership.status, expiresOn: payment.membership.expires_on } : null });
export function createPaymentService({ repository, auditService }) { return {
  async list(filters) { return (await repository.listWithDetails(filters)).map(output); },
  async ownPayments(actor) { const member = await repository.memberByUser(actor.id); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_PROFILE_NOT_FOUND", message: "Tài khoản chưa có hồ sơ hội viên." }); return this.list({ member_id: member.id }); },
  async get(id) { const [payment] = await repository.listWithDetails({ id }); if (!payment) throw new AppError({ statusCode: 404, code: "PAYMENT_NOT_FOUND", message: "Không tìm thấy thanh toán." }); return { ...output(payment), events: await repository.paymentEvents(id) }; },
  async ownReceipt(id, actor) { const member = await repository.memberByUser(actor.id); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_PROFILE_NOT_FOUND", message: "Tài khoản chưa có hồ sơ hội viên." }); const [payment] = await repository.listWithDetails({ id, member_id: member.id }); if (!payment) throw new AppError({ statusCode: 404, code: "PAYMENT_NOT_FOUND", message: "Không tìm thấy phiếu thu của bạn." }); return { ...output(payment), events: await repository.paymentEvents(id) }; },
  async create(input, actorUserId) { const member = await repository.member(input.memberId); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_NOT_FOUND", message: "Không tìm thấy hội viên." }); let amountVnd = BigInt(input.amountVnd); if (input.method === "online" && !input.provider) throw new AppError({ statusCode: 422, code: "PAYMENT_PROVIDER_REQUIRED", message: "Cần chọn cổng thanh toán sandbox." }); if (input.membershipId) { const membership = await repository.membership(input.membershipId); if (!membership || membership.member_id !== input.memberId || membership.status !== "pending_payment") throw new AppError({ statusCode: 422, code: "MEMBERSHIP_PAYMENT_NOT_ELIGIBLE", message: "Gói tập không ở trạng thái chờ thanh toán." }); if (amountVnd !== membership.price_vnd_snapshot) throw new AppError({ statusCode: 422, code: "PAYMENT_AMOUNT_MISMATCH", message: "Số tiền phải khớp giá gói tập đã chốt." }); }
    const method = input.method ?? "cash"; const provider = method === "online" ? input.provider : null; const payment = await repository.createWithEvent({ transaction_code: `PAY-${randomBytes(4).toString("hex").toUpperCase()}`, member_id: input.memberId, membership_id: input.membershipId ?? null, amount_vnd: amountVnd, method, provider, status: "pending", recorded_by: actorUserId, notes: input.notes ?? null }, { event_type: "payment_created", new_status: "pending", actor_user_id: actorUserId }); await auditService.record({ actorUserId, action: "payment.created", entityType: "payment", entityId: payment.id, summary: method === "online" ? `Đã tạo thanh toán sandbox qua ${provider}.` : "Đã lập phiếu thu tiền mặt chờ Lễ tân xác nhận." }); return { ...output(payment), ...(provider && { sandboxPaymentUrl: sandboxPaymentUrl(provider, payment.transaction_code, amountVnd) }) }; },
  async providerCallback(provider, input) { if (!verifySandboxCallback({ provider, ...input })) throw new AppError({ statusCode: 401, code: "PAYMENT_CALLBACK_SIGNATURE_INVALID", message: "Chữ ký callback không hợp lệ." }); const payment = await repository.paymentByCode(input.transactionCode); if (!payment || payment.provider !== provider || payment.amount_vnd !== BigInt(input.amount)) throw new AppError({ statusCode: 422, code: "PAYMENT_CALLBACK_INVALID", message: "Callback không khớp giao dịch." }); const result = await repository.complete({ id: payment.id, status: input.status, paidAt: input.status === "paid" ? new Date() : null, eventType: `${provider}_sandbox_callback`, actorUserId: null, membershipId: payment.membership_id }); return result ? output(result) : output(payment); },
  async confirm(id, status, actorUserId) { const payment = await repository.payment(id); if (!payment || payment.status !== "pending") throw new AppError({ statusCode: 422, code: "PAYMENT_NOT_CONFIRMABLE", message: "Giao dịch không còn chờ xác nhận." }); const result = await repository.complete({ id, status, paidAt: status === "paid" ? new Date() : null, eventType: "receptionist_cash_confirmation", actorUserId, membershipId: payment.membership_id }); if (!result) throw new AppError({ statusCode: 409, code: "PAYMENT_ALREADY_CONFIRMED", message: "Giao dịch đã được xử lý bởi một xác nhận khác." }); await auditService.record({ actorUserId, action: `payment.${status}`, entityType: "payment", entityId: id, summary: status === "paid" ? "Lễ tân đã xác nhận đã thu tiền mặt và kích hoạt gói tập." : "Lễ tân xác nhận phiếu thu tiền mặt không thành công." }); return output(result); },
}; }
