import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { AppError } from "../../shared/errors/app-error.js";
const output = (payment) => ({ ...payment, amountVnd: payment.amount_vnd.toString() });
export function createPaymentService({ repository, auditService }) { return {
  async list(filters) { return (await repository.list(filters)).map(output); },
  async ownPayments(actor) { const member = await repository.memberByUser(actor.id); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_PROFILE_NOT_FOUND", message: "Tài khoản chưa có hồ sơ hội viên." }); return this.list({ member_id: member.id }); },
  async get(id) { const payment = await repository.payment(id); if (!payment) throw new AppError({ statusCode: 404, code: "PAYMENT_NOT_FOUND", message: "Không tìm thấy thanh toán." }); return output(payment); },
  async create(input, actorUserId) { const member = await repository.member(input.memberId); if (!member) throw new AppError({ statusCode: 404, code: "MEMBER_NOT_FOUND", message: "Không tìm thấy hội viên." }); let amountVnd = BigInt(input.amountVnd); if (input.membershipId) { const membership = await repository.membership(input.membershipId); if (!membership || membership.member_id !== input.memberId || membership.status !== "pending_payment") throw new AppError({ statusCode: 422, code: "MEMBERSHIP_PAYMENT_NOT_ELIGIBLE", message: "Gói tập không ở trạng thái chờ thanh toán." }); if (amountVnd !== membership.price_vnd_snapshot) throw new AppError({ statusCode: 422, code: "PAYMENT_AMOUNT_MISMATCH", message: "Số tiền phải khớp giá gói tập đã chốt." }); }
    const payment = await repository.createWithEvent({ transaction_code: `PAY-${randomBytes(4).toString("hex").toUpperCase()}`, member_id: input.memberId, membership_id: input.membershipId ?? null, amount_vnd: amountVnd, method: input.method, provider: input.provider ?? null, status: "pending", recorded_by: actorUserId, notes: input.notes ?? null }, { event_type: "payment_created", new_status: "pending", actor_user_id: actorUserId }); await auditService.record({ actorUserId, action: "payment.created", entityType: "payment", entityId: payment.id, summary: "Đã tạo giao dịch chờ xác nhận." }); return output(payment); },
  async confirm(id, status, actorUserId, source = "receptionist") { const payment = await repository.payment(id); if (!payment || payment.status !== "pending") throw new AppError({ statusCode: 422, code: "PAYMENT_NOT_CONFIRMABLE", message: "Giao dịch không còn chờ xác nhận." }); if (source === "receptionist" && payment.method === "online") throw new AppError({ statusCode: 422, code: "ONLINE_PAYMENT_PROVIDER_REQUIRED", message: "Giao dịch trực tuyến phải được xác nhận từ cổng thanh toán." }); const result = await repository.complete({ id, status, paidAt: status === "paid" ? new Date() : null, eventType: `${source}_confirmation`, actorUserId, membershipId: payment.membership_id }); if (!result) throw new AppError({ statusCode: 409, code: "PAYMENT_ALREADY_CONFIRMED", message: "Giao dịch đã được xử lý bởi một xác nhận khác." }); await auditService.record({ actorUserId, action: `payment.${status}`, entityType: "payment", entityId: id, summary: status === "paid" ? "Đã xác nhận thanh toán và kích hoạt gói tập." : "Thanh toán không thành công." }); return output(result); },
  async providerCallback(provider, payload, signature, secret) { const digest = createHmac("sha256", secret).update(JSON.stringify(payload)).digest("hex"); if (!signature || signature.length !== digest.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(digest))) throw new AppError({ statusCode: 401, code: "INVALID_PROVIDER_SIGNATURE", message: "Chữ ký cổng thanh toán không hợp lệ." }); const payment = await repository.paymentByCode(payload.transactionCode); if (!payment || payment.provider !== provider || payment.amount_vnd !== BigInt(payload.amountVnd)) throw new AppError({ statusCode: 422, code: "PROVIDER_PAYMENT_MISMATCH", message: "Dữ liệu giao dịch không khớp." }); if (payment.status !== "pending") return output(payment); return this.confirm(payment.id, payload.status === "success" ? "paid" : "failed", null, provider); },
}; }
