import { Router } from "express";
import { z } from "zod";
import { authenticate, requirePermission } from "../../shared/auth/authentication.middleware.js";
import { sendSuccess } from "../../shared/http/response.js";
import { validateRequest } from "../../shared/validation/validate-request.js";
const id = z.string().uuid();
export function createPaymentRouter(service, authService) { const router = Router(); const read = [authenticate(authService), requirePermission("payment.read")]; const secure = [authenticate(authService), requirePermission("payment.record")]; const payload = z.object({ memberId: id, membershipId: id.optional(), amountVnd: z.coerce.number().int().positive(), method: z.enum(["cash", "online"]).optional(), provider: z.enum(["vnpay", "momo", "zalopay", "payos"]).optional(), notes: z.string().trim().max(500).optional() }).strict().superRefine((value, context) => { if (value.method === "online" && !value.provider) context.addIssue({ code: "custom", path: ["provider"], message: "Cần chọn cổng thanh toán." }); }); const sandboxParams = z.object({ params: z.object({ provider: z.enum(["vnpay", "momo", "zalopay"]), transactionCode: z.string().regex(/^PAY-[A-F0-9]{8}$/) }), query: z.object({ amount: z.coerce.number().int().positive(), signature: z.string().regex(/^[a-f0-9]{64}$/) }) });
  router.get("/members/me/payments", authenticate(authService), async (req, res, next) => { try { sendSuccess(res, { data: await service.ownPayments(req.auth.user) }); } catch (error) { next(error); } });
  router.get("/members/me/payments/:id", authenticate(authService), validateRequest(z.object({ params: z.object({ id }) })), async (req, res, next) => { try { sendSuccess(res, { data: await service.ownReceipt(req.validated.params.id, req.auth.user) }); } catch (error) { next(error); } });
  router.get("/payments", ...read, async (req, res, next) => { try { sendSuccess(res, { data: await service.list(req.query.memberId ? { member_id: req.query.memberId } : undefined) }); } catch (error) { next(error); } });
  router.post("/payments", ...secure, validateRequest(z.object({ body: payload })), async (req, res, next) => { try { sendSuccess(res, { statusCode: 201, data: await service.create(req.validated.body, req.auth.user.id) }); } catch (error) { next(error); } });
  router.get("/payments/sandbox/:provider/:transactionCode", validateRequest(sandboxParams), (req, res) => { const { provider, transactionCode } = req.validated.params; const { amount, signature } = req.validated.query; const callbackUrl = `${req.baseUrl}/payments/callbacks/${provider}`; const callback = JSON.stringify({ transactionCode, status: "paid", amount, signature }); res.type("html").send(`<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${provider.toUpperCase()} Sandbox</title><style>body{font-family:system-ui,sans-serif;background:#f5f7fb;margin:0;padding:32px;color:#172033}.card{max-width:440px;margin:auto;background:#fff;border-radius:16px;padding:28px;box-shadow:0 8px 24px #15203818}button{width:100%;padding:12px;border:0;border-radius:8px;background:#126de5;color:#fff;font-weight:700;cursor:pointer}#status{min-height:24px;color:#46546d}</style><main class="card"><p>${provider.toUpperCase()} · môi trường kiểm thử</p><h1>Thanh toán sandbox</h1><p>Mã giao dịch: <strong>${transactionCode}</strong></p><p>Số tiền: <strong>${amount.toLocaleString("vi-VN")} ₫</strong></p><button id="pay">Mô phỏng thanh toán thành công</button><p id="status"></p></main><script>const button=document.getElementById('pay'),status=document.getElementById('status');button.onclick=async()=>{button.disabled=true;status.textContent='Đang xử lý…';try{const response=await fetch(${JSON.stringify(callbackUrl)},{method:'POST',headers:{'Content-Type':'application/json'},body:${JSON.stringify(callback)}});if(!response.ok)throw new Error('Callback thất bại');status.textContent='Thanh toán sandbox thành công. Bạn có thể quay lại ứng dụng.'}catch(error){button.disabled=false;status.textContent='Không thể xử lý thanh toán. Vui lòng thử lại.'}}</script></html>`); });
  router.get("/payments/:id", ...read, validateRequest(z.object({ params: z.object({ id }) })), async (req, res, next) => { try { sendSuccess(res, { data: await service.get(req.validated.params.id) }); } catch (error) { next(error); } });
  router.post("/payments/:id/confirm", ...secure, validateRequest(z.object({ params: z.object({ id }), body: z.object({ status: z.enum(["paid", "failed"]) }) })), async (req, res, next) => { try { sendSuccess(res, { data: await service.confirm(req.validated.params.id, req.validated.body.status, req.auth.user.id) }); } catch (error) { next(error); } });
  router.post("/payments/callbacks/payos", async (req, res, next) => { try { sendSuccess(res, { data: await service.payosCallback(req.body) }); } catch (error) { next(error); } });
  router.post("/payments/callbacks/:provider", validateRequest(z.object({ params: z.object({ provider: z.enum(["vnpay", "momo", "zalopay"]) }), body: z.object({ transactionCode: z.string().min(1), status: z.enum(["paid", "failed"]), amount: z.coerce.number().int().positive(), signature: z.string().min(1) }) })), async (req, res, next) => { try { sendSuccess(res, { data: await service.providerCallback(req.validated.params.provider, req.validated.body) }); } catch (error) { next(error); } });
  return router;
}
