import { randomBytes } from "node:crypto";
import { AppError } from "../../shared/errors/app-error.js";

export function createClassService({ repository, auditService }) {
  return {
    list: () => repository.list(),
    changes: (status) => repository.changes(status),
    rooms: () => repository.rooms(),
    coaches: () => repository.coaches(),
    async create(input, actorUserId) { if (!await repository.findRoom(input.roomId)) throw new AppError({ statusCode: 422, code: "ROOM_NOT_FOUND", message: "Không tìm thấy phòng học." }); if (!await repository.findCoach(input.coachUserId)) throw new AppError({ statusCode: 422, code: "COACH_NOT_AVAILABLE", message: "Huấn luyện viên không khả dụng." }); const starts = new Date(input.startsAt); const ends = new Date(input.endsAt); if (ends <= starts) throw new AppError({ statusCode: 422, code: "INVALID_CLASS_TIME", message: "Giờ kết thúc phải sau giờ bắt đầu." }); const result = await repository.create({ code: `CLS-${randomBytes(4).toString("hex").toUpperCase()}`, name: input.name, type: input.type, description: input.description ?? null, coach_user_id: input.coachUserId, room_id: input.roomId, starts_at: starts, ends_at: ends, capacity: input.capacity, created_by: actorUserId }); await auditService.record({ actorUserId, action: "class.created", entityType: "class_session", entityId: result.id, summary: "Đã tạo lớp học ở trạng thái nháp." }); return result; },
    async update(id, input, actorUserId) { const current = await repository.find(id); if (!current) throw new AppError({ statusCode: 404, code: "CLASS_NOT_FOUND", message: "Không tìm thấy lớp học." }); if (input.roomId && !await repository.findRoom(input.roomId)) throw new AppError({ statusCode: 422, code: "ROOM_NOT_FOUND", message: "Không tìm thấy phòng học." }); if (input.coachUserId && !await repository.findCoach(input.coachUserId)) throw new AppError({ statusCode: 422, code: "COACH_NOT_AVAILABLE", message: "Huấn luyện viên không khả dụng." }); const startsAt = input.startsAt ? new Date(input.startsAt) : current.starts_at; const endsAt = input.endsAt ? new Date(input.endsAt) : current.ends_at; if (endsAt <= startsAt) throw new AppError({ statusCode: 422, code: "INVALID_CLASS_TIME", message: "Giờ kết thúc phải sau giờ bắt đầu." }); const result = await repository.update(id, { ...(input.name !== undefined && { name: input.name }), ...(input.type !== undefined && { type: input.type }), ...(input.description !== undefined && { description: input.description || null }), ...(input.coachUserId !== undefined && { coach_user_id: input.coachUserId }), ...(input.roomId !== undefined && { room_id: input.roomId }), ...(input.startsAt !== undefined && { starts_at: startsAt }), ...(input.endsAt !== undefined && { ends_at: endsAt }), ...(input.capacity !== undefined && { capacity: input.capacity }), ...(input.status && { status: input.status }) }); await auditService.record({ actorUserId, action: "class.updated", entityType: "class_session", entityId: id, summary: "Đã cập nhật lớp học." }); return result; },
    async publish(id, actorUserId) { return this.update(id, { status: "published" }, actorUserId); },
    async requestChange(classId, input, actor) { const session = await repository.find(classId); if (!session || session.coach_user_id !== actor) throw new AppError({ statusCode: 403, code: "CLASS_CHANGE_NOT_ALLOWED", message: "Chỉ coach phụ trách lớp mới được đề xuất thay đổi." }); const result = await repository.createChange({ class_session_id: classId, type: input.type, proposed_starts_at: input.startsAt ? new Date(input.startsAt) : null, proposed_ends_at: input.endsAt ? new Date(input.endsAt) : null, reason: input.reason, requested_by: actor }); await auditService.record({ actorUserId: actor, action: "class.change_requested", entityType: "class_session", entityId: classId, summary: "Coach đã đề xuất thay đổi lớp.", reason: input.reason }); return result; },
    async reviewChange(id, approved, actor) { const change = await repository.change(id); if (!change || change.status !== "pending") throw new AppError({ statusCode: 422, code: "CLASS_CHANGE_UNAVAILABLE", message: "Yêu cầu thay đổi không còn chờ duyệt." }); const result = await repository.reviewChange(id, approved ? "approved" : "rejected", actor); if (approved) { if (change.type === "cancel") await repository.update(change.class_session_id, { status: "cancelled" }); else await repository.update(change.class_session_id, { starts_at: change.proposed_starts_at, ends_at: change.proposed_ends_at }); await repository.cancelBookings(change.class_session_id); await repository.notifyClassMembers(change.class_session_id, change.type === "cancel" ? "Lớp học đã hủy" : "Lớp học đã đổi lịch", change.type === "cancel" ? "Booking đã được hủy, bạn không bị tính phạt." : "Booking đã được hủy để bạn chọn lại lịch phù hợp, bạn không bị tính phạt."); } await auditService.record({ actorUserId: actor, action: approved ? "class.change_approved" : "class.change_rejected", entityType: "class_session", entityId: change.class_session_id, summary: approved ? "Đã duyệt thay đổi lớp và thông báo hội viên." : "Đã từ chối thay đổi lớp." }); return result; },
  };
}
