import { useState } from "react";
import { Button } from "../../components/ui/Button.jsx";
import { attendanceApi } from "./attendance-api.js";

const statusLabels = { present: "Có mặt", absent: "Vắng", late: "Đi trễ", not_marked: "Chưa ghi nhận" };
export function AttendancePage() { const [bookingId, setBookingId] = useState(""); const [classId, setClassId] = useState(""); const [records, setRecords] = useState([]); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  async function refresh() { setRecords(await attendanceApi.byClass(classId)); }
  async function checkIn(event) { event.preventDefault(); setError(""); setNotice(""); try { await attendanceApi.checkIn(bookingId); setBookingId(""); setNotice("Đã check-in cho buổi học."); } catch (requestError) { setError(requestError.message); } }
  async function loadRecords(event) { event.preventDefault(); setError(""); try { await refresh(); } catch (requestError) { setError(requestError.message); } }
  async function checkOut(id) { setError(""); setNotice(""); try { await attendanceApi.checkOut(id); await refresh(); setNotice("Đã check-out buổi học."); } catch (requestError) { setError(requestError.message); } }
  async function correct(record) { const status = window.prompt("Trạng thái mới: present, absent, late hoặc not_marked", record.status); if (!status) return; const reason = window.prompt("Lý do sửa điểm danh (ít nhất 3 ký tự):"); if (!reason) return; setError(""); try { await attendanceApi.correct(record.id, { status, reason }); await refresh(); setNotice("Đã sửa điểm danh và lưu audit."); } catch (requestError) { setError(requestError.message); } }
  return <main className="members-page"><header><p>Điểm danh</p><h1>Điểm danh theo buổi học</h1></header>{error && <p className="auth-alert">{error}</p>}{notice && <p className="auth-notice">{notice}</p>}<div className="members-grid"><form className="members-form" onSubmit={checkIn}><h2>Check-in theo booking</h2><label>Mã booking<input value={bookingId} onChange={(event) => setBookingId(event.target.value)} placeholder="UUID booking" required /></label><Button type="submit">Xác nhận check-in</Button><small>Mỗi booking của một buổi học chỉ tạo một lượt điểm danh.</small></form><section className="members-list"><form className="members-form" onSubmit={loadRecords}><h2>Danh sách điểm danh lớp</h2><label>Mã lớp<input value={classId} onChange={(event) => setClassId(event.target.value)} placeholder="UUID lớp học" required /></label><Button type="submit" variant="secondary">Tải danh sách</Button></form>{records.length > 0 && <table><thead><tr><th>Hội viên</th><th>Trạng thái</th><th>Check-in</th><th>Check-out</th><th>Thao tác</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><code>{record.member_id}</code></td><td>{statusLabels[record.status] ?? record.status}</td><td>{record.checked_in_at ? new Date(record.checked_in_at).toLocaleString("vi-VN") : "—"}</td><td>{record.checked_out_at ? new Date(record.checked_out_at).toLocaleString("vi-VN") : "—"}</td><td>{record.status === "present" && !record.checked_out_at && <Button type="button" variant="secondary" onClick={() => checkOut(record.id)}>Check-out</Button>} <Button type="button" variant="ghost" size="sm" onClick={() => correct(record)}>Sửa</Button></td></tr>)}</tbody></table>}</section></div></main>; }
