import { randomBytes } from "node:crypto";
import { AppError } from "../../shared/errors/app-error.js";
import { hashPassword } from "../../shared/auth/password.js";
const roles = new Set(["manager", "receptionist", "coach"]);
const view = (staff) => ({ id: staff.id, employeeCode: staff.staff_profiles?.employee_code, fullName: staff.display_name, email: staff.email, role: staff.role, status: staff.status, phone: staff.staff_profiles?.phone, dateOfBirth: staff.staff_profiles?.date_of_birth, notes: staff.staff_profiles?.notes, specialties: staff.staff_profiles?.specialties ?? [], lastLoginAt: staff.last_login_at, createdAt: staff.created_at });
export function createStaffService({ repository, auditService }) { return {
  async list() { return (await repository.list()).map(view); }, async get(id) { const staff = await repository.find(id); if (!staff) throw new AppError({ statusCode: 404, code: "STAFF_NOT_FOUND", message: "Không tìm thấy nhân viên." }); return view(staff); },
  async create(input, actorUserId) { if (!roles.has(input.role)) throw new AppError({ statusCode: 422, code: "INVALID_STAFF_ROLE", message: "Vai trò nhân sự không hợp lệ." }); if (await repository.findByEmail(input.email.toLowerCase())) throw new AppError({ statusCode: 409, code: "STAFF_EMAIL_EXISTS", message: "Email này đã được sử dụng." }); const temporaryPassword = randomBytes(12).toString("base64url"); const employeeCode = `STF-${randomBytes(4).toString("hex").toUpperCase()}`; const staff = await repository.create({ ...input, email: input.email.toLowerCase(), employeeCode, passwordHash: await hashPassword(temporaryPassword), dateOfBirth: input.dateOfBirth ? new Date(input.dateOfBirth) : null }); await auditService.record({ actorUserId, action: "staff.created", entityType: "staff", entityId: staff.id, summary: "Đã tạo tài khoản nhân viên.", newValue: { role: staff.role } }); return { staff: view(staff), temporaryPassword }; },
  async update(id, input, actorUserId) { const before = await this.get(id); const staff = await repository.update(id, { ...input, dateOfBirth: input.dateOfBirth ? new Date(input.dateOfBirth) : undefined }); await auditService.record({ actorUserId, action: "staff.updated", entityType: "staff", entityId: id, summary: "Đã cập nhật nhân viên.", previousValue: { role: before.role }, newValue: { role: staff.role } }); return view(staff); },
  async setStatus(id, status, actorUserId) { if (!["active", "suspended"].includes(status)) throw new AppError({ statusCode: 422, code: "INVALID_STAFF_STATUS", message: "Trạng thái không hợp lệ." }); const before = await this.get(id); const staff = await repository.setStatus(id, status); await auditService.record({ actorUserId, action: `staff.${status}`, entityType: "staff", entityId: id, summary: status === "suspended" ? "Đã đình chỉ nhân viên." : "Đã kích hoạt lại nhân viên.", previousValue: { status: before.status }, newValue: { status } }); return view({ ...before, ...staff }); },
}; }
