import { expect, test } from "@playwright/test";
import { isolatedQaPassword } from "./isolated-qa-password.js";

test("member books a published class with an active QA entitlement", async ({ page }) => {
  test.skip(process.env.E2E_QA_WRITE !== "1" || process.env.E2E_BASE_URL !== "http://localhost:5175", "Bookings are restricted to isolated QA.");
  const className = `Lớp QA đặt chỗ ${Date.now().toString(36).toUpperCase()}`;
  await page.goto("/login");
  await page.locator("#login-email").fill("qa-manager@localhost.test");
  await page.locator("#login-password").fill(isolatedQaPassword());
  await page.getByRole("button", { name: "Đăng nhập", exact: true }).click();
  await expect(page.locator(".app-header strong")).toBeVisible();
  await page.goto("/classes");
  const classForm = page.locator("form.classes-create-form");
  const start = new Date();
  start.setDate(start.getDate() + 2 + Math.floor(Math.random() * 20));
  start.setHours(8 + Math.floor(Math.random() * 10), 0, 0, 0);
  const end = new Date(start.getTime() + 60 * 60 * 1000);
  const localDateTime = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}T${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
  await classForm.getByLabel("Tên lớp").fill(className);
  await classForm.getByLabel("Coach").selectOption({ index: 1 });
  await classForm.getByLabel("Phòng").selectOption({ index: 1 });
  await classForm.getByLabel("Bắt đầu").fill(localDateTime(start));
  await classForm.getByLabel("Kết thúc").fill(localDateTime(end));
  await classForm.getByLabel("Sức chứa").fill("10");
  await classForm.getByRole("button", { name: "Tạo lớp nháp" }).click();
  await page.getByRole("searchbox", { name: "Tìm ID, tên hoặc loại lớp..." }).fill(className);
  const row = page.getByRole("row").filter({ hasText: className });
  await expect(row).toBeVisible();
  await row.getByRole("button", { name: "Công bố" }).click();
  await expect(row.getByText("Đã công bố", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Đăng xuất" }).click();

  await page.goto("/login");
  await page.locator("#login-email").fill("qa-member@localhost.test");
  await page.locator("#login-password").fill(isolatedQaPassword());
  await page.getByRole("button", { name: "Đăng nhập", exact: true }).click();
  await expect(page.locator(".app-header strong")).toBeVisible();
  await page.goto("/bookings");
  const form = page.locator("form.members-form--booking-create-member");
  await form.getByRole("button", { name: "Đặt chỗ", exact: true }).click();
  await expect(page.getByText("Hãy chọn lớp học trước khi đặt chỗ.").first()).toBeVisible();
  await form.locator(".class-session-select__trigger").click();
  const option = form.getByRole("option").filter({ hasText: className });
  await expect(option).toBeVisible();
  await option.click();
  await form.getByRole("button", { name: "Đặt chỗ", exact: true }).click();
  const bookingRow = page.getByRole("row").filter({ hasText: className }).first();
  await expect(bookingRow).toBeVisible();
  await expect(bookingRow.getByText("Đã xác nhận")).toBeVisible();
  await bookingRow.getByRole("button", { name: "Hủy" }).click();
  const dialog = page.getByRole("dialog", { name: "Hủy đặt chỗ" });
  await dialog.getByLabel("Lý do hủy").fill("Kiểm thử hủy booking trên QA");
  await dialog.getByRole("button", { name: "Xác nhận hủy" }).click();
  await expect(bookingRow.getByText("Đã hủy")).toBeVisible();
});
